"""Chrome-based PDF generation via Playwright (headless Chromium).

Why this exists alongside utils/pdf_utils.py (WeasyPrint):
WeasyPrint and Chromium are different CSS engines. The Resume Editor's
canvas is rendered by Chromium (the user's browser), so when the PDF was
generated by WeasyPrint, the page-break positions in the editor preview
didn't match the PDF's actual page breaks.

Using headless Chromium for PDF generation guarantees the editor's preview
and the exported PDF use the SAME rendering engine, so pagination matches.

Cost: spawning Chromium per request is slower (~500ms cold) than
WeasyPrint. For a single-user dev tool this is fine. If we need scale we
could keep a browser instance warm.
"""
import asyncio
from typing import Optional

from playwright.async_api import async_playwright


async def html_to_pdf_chrome(html: str) -> Optional[bytes]:
    """Convert HTML string to PDF bytes via headless Chromium."""
    try:
        async with async_playwright() as p:
            # `chromium.launch()` uses the Chrome Headless Shell installed
            # via `playwright install chromium`.
            browser = await p.chromium.launch()
            try:
                page = await browser.new_page()
                # `set_content` waits for the load event by default. networkidle
                # would wait too long if there are no external requests.
                await page.set_content(html, wait_until="load")
                pdf = await page.pdf(
                    format="Letter",
                    print_background=True,
                    margin={"top": "0", "bottom": "0", "left": "0", "right": "0"},
                    prefer_css_page_size=True,
                )
                return pdf
            finally:
                await browser.close()
    except Exception as e:  # noqa: BLE001 — broad catch matches utils/pdf_utils.py
        print(f"[DEBUG] Chrome PDF conversion error: {e}")
        return None


def html_to_pdf_chrome_sync(html: str) -> Optional[bytes]:
    """Synchronous wrapper around html_to_pdf_chrome for non-async callers.

    Creates a new event loop if none exists; reuses the running loop otherwise.
    Inside FastAPI route handlers (which are already async), call the async
    version directly with `await` instead.
    """
    try:
        loop = asyncio.get_event_loop()
        if loop.is_running():
            # Running inside an async context — caller should use async version.
            # Fall back to running in a thread with a new loop.
            import concurrent.futures

            def _run() -> Optional[bytes]:
                return asyncio.run(html_to_pdf_chrome(html))

            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as ex:
                return ex.submit(_run).result()
    except RuntimeError:
        pass
    return asyncio.run(html_to_pdf_chrome(html))
